### ISSUE TITLE
Rename project to `edge15-connector`?

### ISSUE THREAD

**Issue by alrra** [sonarwhal/connector-edge15#2]
Cc: @sonarwhal/contributors

**Comment by molant** [comment]
Not sure, I think k it is nice to have the type before (connector-, rule-) but I don't have a strong opinion.

**Comment by sarvaje** [comment]
I don't have a strong opinion neither.

**Comment by molant** [comment]
Let's rename it then. It sounds better :)
@sarvaje can you update your code? I've renamed the repo.

**Comment by alrra** [comment]
>  I think k it is nice to have the type before (connector-, rule-)

Actually, after seeing the `package.json` file and thinking about the `npm` scenario, `connector-edge15` makes more sense.
